
services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: akezanna
      MINIO_ROOT_PASSWORD: akezanna
    command: server /data --console-address :9000
    ports:
      - "9000:9000"    # MinIO API Port
      - "9001:9001"    # MinIO Console Port
    volumes:
      - minio-data:/data
        
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ak_tasks_db'
      - 'POSTGRES_PASSWORD=akezanna'
      - 'POSTGRES_USER=akezanna'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    minio-data:
    postgres-data:
