version: "3.8"

services:
  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: ${KANFLOW_POSTGRES_DB}
      POSTGRES_USER: ${KANFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KANFLOW_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  minio-data:
  postgres-data:
